{% set name = "pcstf" %}
{% set version = "1.0.10.post1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 371506e0655950a121e4d6ee80ddf63c714c7c7dcee83eb11dbe3bbacc89a13c

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"

requirements:
  host:
    - pip
    - pybind11 >=2.1.0
    - python
    - setuptools >=40.8.0
  run:
    - pybind11 >=2.1.0
    - python
    - setuptools >=40.8.0

test:
  imports:
    - pcst_fast

about:
  home: "https://github.com/fraenkel-lab/pcst_fast"
  license: GNU General Public
  license_family: GPL
  license_file: 
  summary: "A fast implementation of the Goemans-Williamson scheme for the prize-collecting Steiner tree / forest problem."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
